version: '3'
services:
  frontend:
    build: frontend/    # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always # Reiniciamos o container sempre.
    ports: 
      - 3000:3000
    depends_on:
      - backend # Especificamos a dependência do serviço backend.
    volumes:
      - ./frontend/src:/frontend/src # Montamos um volume para o diretório src.
    networks:
      - rede-virtual-1 # Especificamos a rede virtual.
  backend:
    build: backend/     # Mesmo caso aqui.
    restart: always
    ports: 
      - 3001:3001
    environment:
      - DB_HOST=database # Especificamos a variável de ambiente DB_HOST.
    depends_on:
      - database # Especificamos a dependência do serviço database.
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1    # Especificamos a Imagem Docker diretamente.
    restart: always
    networks:
      - rede-virtual-2
      
volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2: